kind: ProviderConfig
metadata:
  name: grafana-provider
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: grafana-credentials
      key: credentials
  endpoint: https://<SLUG>.grafana.net
